repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: check-added-large-files
        args: ["--maxkb=150000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
        files: ^py-coitrees/
      - id: ruff-format
        files: ^py-coitrees/
